CREATE TABLE `user_` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `EMAIL_ADDRESS` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) 


CREATE TABLE `movie` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(100) NOT NULL,
  `GENRE` varchar(100) NOT NULL,
  `RELEASE_YEAR` int NOT NULL,
  `RENTAL_PRICE` decimal(10,0) NOT NULL,
  `NO_OF_COPIES` int NOT NULL,
  PRIMARY KEY (`ID`)
) 

CREATE TABLE `rental` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint NOT NULL,
  `MOVIES_ID` bigint NOT NULL,
  `RENTAL_DATE` datetime NOT NULL,
  `DUE_DATE` datetime NOT NULL,
  `RETURNED` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `RENTALS_FK` (`MOVIES_ID`),
  KEY `RENTALS_FK_1` (`USER_ID`),
  CONSTRAINT `RENTALS_FK` FOREIGN KEY (`MOVIES_ID`) REFERENCES `movie` (`ID`),
  CONSTRAINT `RENTALS_FK_1` FOREIGN KEY (`USER_ID`) REFERENCES `user_` (`ID`)
) 



